### ISSUE TITLE
Widgetpicker not working anymore on (newer) Xiaomi devices

### ISSUE THREAD

**Issue by Coyenzo** [ns130291/widgets-for-auto#2]
I know this app isn't updated for quite a while now, but I refuse to live without this app :-) On newer Xiaomi models the widgetpicker isn't working anymore. (see for extra info #https://github.com/Neamar/KISS/issues/1733) Any chance of updating the app with the solution on that issue? #https://github.com/Neamar/KISS/pull/1954

**Comment by ns130291** [comment]
I've uploaded a new release with the picker from KISS: https://github.com/ns130291/widgets-for-auto/releases/tag/v0.2.1
Please check it out and report back!

**Comment by Coyenzo** [comment]
Wow, thanks for the update and response! I'm getting a little bit further, but unfortunately not all the way... When I hit the button 'add widget' the new widgetpicker is coming up, but when I select any widget it crashes again. On my old Xiaomi phone it asks if I want to allow widgets for auto to place an access the widget, but on the new Xiaomi just the crash. Maybe some asking permission issue?

**Comment by ns130291** [comment]
Does the KISS launcher add widget process work on your newer Xiaomi device?
Can you take logcat logs of my app when crashing?

**Comment by Coyenzo** [comment]
I'm away for the weekend, I'll check Monday evening and will let you know!

**Comment by petous22** [comment]
For me the same problem on Xiaomi 13.

**Comment by Coyenzo** [comment]
Kiss launcher is working fine on my new Xiaomi; when selecting a widget, it comes with the same prompt as mentioned above. (Create Widget and give access to it?) See attached screenrecorder-file. I also tried to get the logcat when opening Widgets for auto and the crash after selecting a widget, I also attached that; hope this helps!

https://github.com/ns130291/widgets-for-auto/assets/76050839/84f00dba-8ac3-4275-849a-015e18a8dae6

[crashlog.txt](https://github.com/ns130291/widgets-for-auto/files/11722543/crashlog.txt)

**Comment by ns130291** [comment]
With help of the logcat and the video I've located one possible root cause for the crash.
I've prepared a debug build which will install as an additional app: https://www.dropbox.com/s/4h4x6ja04hnqiae/widgets4auto-0.2.1-debug.apk?dl=0
If it crashes again I will need a new logcat.

**Comment by Coyenzo** [comment]
Amazing, this version is working like a charm! No force closes and even no glitches which I often have on my old phone with the old version. I'm not yet able to test in my car if it shows up in Android Auto, but I can't imagine that being a problem; I can root my phone after next weekend then I'll also test that.

Thank you so very much! Do you maybe have Paypal or something like it, 'cause I'd definitely want to buy you a couple of beers :-) I was really thinking about selling my new phone already and buying another one, so you saved me a lot of euro's.

**Comment by ns130291** [comment]
Can you please test this version also: https://www.dropbox.com/s/iwh2memdga8d42l/widgets4auto-0.2.1-debug-2.apk?dl=0
I made a small change and want to verify it is still working for you.

My Paypal link: paypal.me/ns130291

**Comment by Coyenzo** [comment]
Tested and also works fine, but not able to test in Android Auto yet. I see no difference with the debug version you sent earlier.

**Comment by ns130291** [comment]
new release version 0.2.2 has all the fixes included: https://github.com/ns130291/widgets-for-auto/releases/tag/v0.2.2
