### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by scheuerer** [ns130291/widgets-for-auto#3]
After selecting a widget I get a "runtime" error.... VIVO X60 Phone under Android 13

**Comment by ns130291** [comment]
can you try the debug build from #2 ?

**Comment by scheuerer** [comment]
Thanks for this fast reaction.
I have downladed the "debug" version and I was able to install it.
Configuration and selecting an "widget" was also possible.
BUT:
- The mail widget from my samsung which I have selected, has only a smal read icon in the selctings wizard,
- Whatever Widget I select, has only the same view in AA itself "no new message during drive"

PIC1:  
![PIC1](https://github.com/ns130291/widgets-for-auto/assets/59388391/bba904a7-9269-46c3-93e5-017a8c4cdbb6)
![PIC2](https://github.com/ns130291/widgets-for-auto/assets/59388391/248e36b0-e862-4c1a-aa00-13629267c40b)
![PIC3](https://github.com/ns130291/widgets-for-auto/assets/59388391/39111e58-15a6-42c1-8d23-82f65563d046)
![PIC4](https://github.com/ns130291/widgets-for-auto/assets/59388391/04211b61-4e33-4037-aa76-76fb2ef052de)
![PIC5](https://github.com/ns130291/widgets-for-auto/assets/59388391/a66d460f-a521-4341-bf20-89f846cfcfc2)
![PIC6](https://github.com/ns130291/widgets-for-auto/assets/59388391/a0f8d587-549b-45f3-b3bb-a0ec4307d82c)

PIC1: Installation has worked, Icon is there.
PIC2: Scrolling in the widgets
PIC3: choosen the Samsung mail widget
PIC4: Only a small icon is displayed after selecting the samsung mail widget
PIC5: APP in AA is there
PIC6: For all Widgets I have installed, I get only this view... Doenst matter if Mail Widget ist selected or a other e.g. weather etc...

**Comment by ns130291** [comment]
To fix the app in Android Auto only showing "no new messages..." you have to use a special installation method or a rooted device as Google only allows apps in AA installed from the Play Store.

I currently know of two non-root methods that work (uninstall the app first):

1. Install the [apk ](https://github.com/ns130291/widgets-for-auto/releases) with https://github.com/fcaronte/KingInstaller
2. ~~Install version 0.2.0 from https://github.com/shmykelsa/AAAD (one free install per 30 days). Afterwards update with the latest release from the [release page](https://github.com/ns130291/widgets-for-auto/releases).~~ Not working as AAAD uses a fork with different application ID and signature

You also need to enable developer options in Android Auto, instructions here: https://9to5google.com/2023/01/25/how-to-enable-developer-mode-in-android-auto-and-why-you-might-want-to/

**Comment by scheuerer** [comment]
Thanks. My mobile has alreday developermode.
Installation from the 0.2.0 via AAAD is ok. Download 0.2.2 and imstall makes two Icons with two different Apps... See here... 
![Screenshot_2023_0614_224035](https://github.com/ns130291/widgets-for-auto/assets/59388391/c5382fa3-bba8-454a-8d8e-cff67b7a68d4)

**Comment by ns130291** [comment]
After much investigation I found out why both of my described installation methods did not work. # 1 didn't work because of Google having blacklisted my current application ID in Android Auto. # 2 doesn't work as AAAD uses a fork of my app with different application ID and signature and therefore a update with my new version is not possible.

So I changed the application ID and now you should be able to install [v0.2.3](https://github.com/ns130291/widgets-for-auto/releases/tag/v0.2.3) with variant 1.

**Comment by scheuerer** [comment]
GREAT TO SEE IT WORKS !!!! Perfect job....
How can I have more than one widget enabled? e.g. I have three different Mailboxes in use?

**Comment by ns130291** [comment]
At the moment only one widget is supported.
For future versions I plan to add multiple layouts to choose from to show more than one widget at a time. Would this fit your usecase or do you have something different in mind?

**Comment by scheuerer** [comment]
Ok, very, very nice to hear, that you plan to support more than one widget.
Main focus for me would be to have more that one inbox in the Mail app. (which is supported by the widget feature in the mail app). With the loosing of feature like the MAP profile in BT for AA and stuff around, and with the fact, that no mail app is direct supported in AA this would be cool. Other apps widgets, like Openhab Client Items for my Smarthome usage, or Tasker Tasks, or e.g. ThinyCam, OpenVPN on/off by a shortcut etc. would be great. So more or less everything what I have on my homescreen as an "one click" action :-) But, thats realy, realy a WOW this evening to see mails on AA on the car :-)

**Comment by scheuerer** [comment]
Here are some examples with BlueMail as Mailclient under AA.
1. Picture is from a C-Class W205 with Lage display and 1920x720pix

![IMG_20230624_122055](https://github.com/ns130291/widgets-for-auto/assets/59388391/716a4c58-5b09-41f5-a043-f407f07a65f5)

2. Picture is from an GLE W166 with smaler display

![IMG_20230623_224816](https://github.com/ns130291/widgets-for-auto/assets/59388391/27cba412-dd23-4ee0-a062-e8a10f7036e9)
